version: "3.9"
services:
  app:
    container_name: todo-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3030
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: db
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    tty: true

  db:
    container_name: todo-db
    image: mysql:8.0.29
    platform: linux/amd64
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - todo-db-data:/var/lib/mysql

volumes:
  todo-db-data:
